name: Test-Object
version: 0.01
abstract: Test an object against all classes it belongs to
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
requires:
  perl: 5.005
  Test::More: 0.47
  File::Spec: 0.82
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
