
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.03
name: Test-Object
author: Adam Kennedy <cpan@ali.as>
license: perl
requires: 
  Test::More: 0.47
  perl: 5.005
  File::Spec: 0.82
abstract: Thoroughly testing objects via registered handlers
